sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.7
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/autoapp.py"
  - export FLASK_DEBUG=1

install:
  - pip install -r requirements/dev.txt
  - python setup.py develop
  - git clone https://github.com/BB-Open/pkan_flask.blazegraph.git
  - cd pkan_flask.blazegraph
  - python setup.py develop

script:
  - pylint src/pkan_flask --output-format=text --disable=R,C0103,W0511,W0703,C0325 # disable Refacturing hints

after_success:
  - codecov