sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.7
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/autoapp.py"
  - export FLASK_DEBUG=1

install:
  -pip install -r requirements/dev.txt

script:
  - pylint src/pkan

after_success:
  - codecov